# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64bd346269d03f78163b380beedef324a39643914bd12b61829534b5ea41ce7313d154a0af1db71e886b5c66752d4616118c9fd1008520517926045dfef626f6

test:
  secret_key_base: 223458c6ef02f4e75f867d22ba692586f9a3fa47cfc9fac552bc3f6504e23c8c1b38cfb29287909a1522e7350aa077a5d0b6df35b897557159256f1cefafbe31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
